services:
  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: secret
    volumes:
      - ./data:/data
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"